export const Spacing = {

  // TOP + LEFT + BOTTOM + RIGHT

  P0: "p-0" as "p-0",
  P1: "p-1" as "p-1",
  P2: "p-2" as "p-2",
  P3: "p-3" as "p-3",
  P0_XS: "p-0-xs" as "p-0-xs",
  P1_XS: "p-1-xs" as "p-1-xs",
  P2_XS: "p-2-xs" as "p-2-xs",
  P3_XS: "p-3-xs" as "p-3-xs",
  P0_SM: "p-0-sm" as "p-0-sm",
  P1_SM: "p-1-sm" as "p-1-sm",
  P2_SM: "p-2-sm" as "p-2-sm",
  P3_SM: "p-3-sm" as "p-3-sm",
  P0_MD: "p-0-md" as "p-0-md",
  P1_MD: "p-1-md" as "p-1-md",
  P2_MD: "p-2-md" as "p-2-md",
  P3_MD: "p-3-md" as "p-3-md",
  P0_LG: "p-0-lg" as "p-0-lg",
  P1_LG: "p-1-lg" as "p-1-lg",
  P2_LG: "p-2-lg" as "p-2-lg",
  P3_LG: "p-3-lg" as "p-3-lg",
  P0_XL: "p-0-xl" as "p-0-xl",
  P1_XL: "p-1-xl" as "p-1-xl",
  P2_XL: "p-2-xl" as "p-2-xl",
  P3_XL: "p-3-xl" as "p-3-xl",

  // RIGHT + LEFT

  PX0: "px-0" as "px-0",
  PX1: "px-1" as "px-1",
  PX2: "px-2" as "px-2",
  PX3: "px-3" as "px-3",
  PX0_SM: "px-0-sm" as "px-0-sm",
  PX1_SM: "px-1-sm" as "px-1-sm",
  PX2_SM: "px-2-sm" as "px-2-sm",
  PX3_SM: "px-3-sm" as "px-3-sm",
  PX0_MD: "px-0-md" as "px-0-md",
  PX1_MD: "px-1-md" as "px-1-md",
  PX2_MD: "px-2-md" as "px-2-md",
  PX3_MD: "px-3-md" as "px-3-md",
  PX0_LG: "px-0-lg" as "px-0-lg",
  PX1_LG: "px-1-lg" as "px-1-lg",
  PX2_LG: "px-2-lg" as "px-2-lg",
  PX3_LG: "px-3-lg" as "px-3-lg",
  PX0_XL: "px-0-xl" as "px-0-xl",
  PX1_XL: "px-1-xl" as "px-1-xl",
  PX2_XL: "px-2-xl" as "px-2-xl",
  PX3_XL: "px-3-xl" as "px-3-xl",

  // TOP + BOTTOM

  PY0: "py-0" as "py-0",
  PY1: "py-1" as "py-1",
  PY2: "py-2" as "py-2",
  PY3: "py-3" as "py-3",
  PY0_SM: "py-0-sm" as "py-0-sm",
  PY1_SM: "py-1-sm" as "py-1-sm",
  PY2_SM: "py-2-sm" as "py-2-sm",
  PY3_SM: "py-3-sm" as "py-3-sm",
  PY0_MD: "py-0-md" as "py-0-md",
  PY1_MD: "py-1-md" as "py-1-md",
  PY2_MD: "py-2-md" as "py-2-md",
  PY3_MD: "py-3-md" as "py-3-md",
  PY0_LG: "py-0-lg" as "py-0-lg",
  PY1_LG: "py-1-lg" as "py-1-lg",
  PY2_LG: "py-2-lg" as "py-2-lg",
  PY3_LG: "py-3-lg" as "py-3-lg",
  PY0_XL: "py-0-xl" as "py-0-xl",
  PY1_XL: "py-1-xl" as "py-1-xl",
  PY2_XL: "py-2-xl" as "py-2-xl",
  PY3_XL: "py-3-xl" as "py-3-xl",

  // LEFT

  PL0: "pl-0" as "pl-0",
  PL1: "pl-1" as "pl-1",
  PL2: "pl-2" as "pl-2",
  PL3: "pl-3" as "pl-3",
  PL0_SM: "pl-0-sm" as "pl-0-sm",
  PL1_SM: "pl-1-sm" as "pl-1-sm",
  PL2_SM: "pl-2-sm" as "pl-2-sm",
  PL3_SM: "pl-3-sm" as "pl-3-sm",
  PL0_MD: "pl-0-md" as "pl-0-md",
  PL1_MD: "pl-1-md" as "pl-1-md",
  PL2_MD: "pl-2-md" as "pl-2-md",
  PL3_MD: "pl-3-md" as "pl-3-md",
  PL0_LG: "pl-0-lg" as "pl-0-lg",
  PL1_LG: "pl-1-lg" as "pl-1-lg",
  PL2_LG: "pl-2-lg" as "pl-2-lg",
  PL3_LG: "pl-3-lg" as "pl-3-lg",
  PL0_XL: "pl-0-xl" as "pl-0-xl",
  PL1_XL: "pl-1-xl" as "pl-1-xl",
  PL2_XL: "pl-2-xl" as "pl-2-xl",
  PL3_XL: "pl-3-xl" as "pl-3-xl",

  // RIGHT

  PR0: "pr-0" as "pr-0",
  PR1: "pr-1" as "pr-1",
  PR2: "pr-2" as "pr-2",
  PR3: "pr-3" as "pr-3",
  PR0_SM: "pr-0-sm" as "pr-0-sm",
  PR1_SM: "pr-1-sm" as "pr-1-sm",
  PR2_SM: "pr-2-sm" as "pr-2-sm",
  PR3_SM: "pr-3-sm" as "pr-3-sm",
  PR0_MD: "pr-0-md" as "pr-0-md",
  PR1_MD: "pr-1-md" as "pr-1-md",
  PR2_MD: "pr-2-md" as "pr-2-md",
  PR3_MD: "pr-3-md" as "pr-3-md",
  PR0_LG: "pr-0-lg" as "pr-0-lg",
  PR1_LG: "pr-1-lg" as "pr-1-lg",
  PR2_LG: "pr-2-lg" as "pr-2-lg",
  PR3_LG: "pr-3-lg" as "pr-3-lg",
  PR0_XL: "pr-0-xl" as "pr-0-xl",
  PR1_XL: "pr-1-xl" as "pr-1-xl",
  PR2_XL: "pr-2-xl" as "pr-2-xl",
  PR3_XL: "pr-3-xl" as "pr-3-xl",

  // TOP

  PT0: "pt-0" as "pt-0",
  PT1: "pt-1" as "pt-1",
  PT2: "pt-2" as "pt-2",
  PT3: "pt-3" as "pt-3",
  PT0_SM: "pt-0-sm" as "pt-0-sm",
  PT1_SM: "pt-1-sm" as "pt-1-sm",
  PT2_SM: "pt-2-sm" as "pt-2-sm",
  PT3_SM: "pt-3-sm" as "pt-3-sm",
  PT0_MD: "pt-0-md" as "pt-0-md",
  PT1_MD: "pt-1-md" as "pt-1-md",
  PT2_MD: "pt-2-md" as "pt-2-md",
  PT3_MD: "pt-3-md" as "pt-3-md",
  PT0_LG: "pt-0-lg" as "pt-0-lg",
  PT1_LG: "pt-1-lg" as "pt-1-lg",
  PT2_LG: "pt-2-lg" as "pt-2-lg",
  PT3_LG: "pt-3-lg" as "pt-3-lg",
  PT0_XL: "pt-0-xl" as "pt-0-xl",
  PT1_XL: "pt-1-xl" as "pt-1-xl",
  PT2_XL: "pt-2-xl" as "pt-2-xl",
  PT3_XL: "pt-3-xl" as "pt-3-xl",


  // BOTTOM

  PB0: "pb-0" as "pb-0",
  PB1: "pb-1" as "pb-1",
  PB2: "pb-2" as "pb-2",
  PB3: "pb-3" as "pb-3",
  PB0_SM: "pb-0-sm" as "pb-0-sm",
  PB1_SM: "pb-1-sm" as "pb-1-sm",
  PB2_SM: "pb-2-sm" as "pb-2-sm",
  PB3_SM: "pb-3-sm" as "pb-3-sm",
  PB0_MD: "pb-0-md" as "pb-0-md",
  PB1_MD: "pb-1-md" as "pb-1-md",
  PB2_MD: "pb-2-md" as "pb-2-md",
  PB3_MD: "pb-3-md" as "pb-3-md",
  PB0_LG: "pb-0-lg" as "pb-0-lg",
  PB1_LG: "pb-1-lg" as "pb-1-lg",
  PB2_LG: "pb-2-lg" as "pb-2-lg",
  PB3_LG: "pb-3-lg" as "pb-3-lg",
  PB0_XL: "pb-0-xl" as "pb-0-xl",
  PB1_XL: "pb-1-xl" as "pb-1-xl",
  PB2_XL: "pb-2-xl" as "pb-2-xl",
  PB3_XL: "pb-3-xl" as "pb-3-xl",


/* -------------------------------------------- */
/*                    MARGINS                   */
/* -------------------------------------------- */

   // TOP + LEFT + BOTTOM + RIGHT

  M0: "m-0" as "m-0",
  M1: "m-1" as "m-1",
  M2: "m-2" as "m-2",
  M3: "m-3" as "m-3",
  M0_XS: "m-0-xs" as "m-0-xs",
  M1_XS: "m-1-xs" as "m-1-xs",
  M2_XS: "m-2-xs" as "m-2-xs",
  M3_XS: "m-3-xs" as "m-3-xs",
  M0_SM: "m-0-sm" as "m-0-sm",
  M1_SM: "m-1-sm" as "m-1-sm",
  M2_SM: "m-2-sm" as "m-2-sm",
  M3_SM: "m-3-sm" as "m-3-sm",
  M0_MD: "m-0-md" as "m-0-md",
  M1_MD: "m-1-md" as "m-1-md",
  M2_MD: "m-2-md" as "m-2-md",
  M3_MD: "m-3-md" as "m-3-md",
  M0_LG: "m-0-lg" as "m-0-lg",
  M1_LG: "m-1-lg" as "m-1-lg",
  M2_LG: "m-2-lg" as "m-2-lg",
  M3_LG: "m-3-lg" as "m-3-lg",
  M0_XL: "m-0-xl" as "m-0-xl",
  M1_XL: "m-1-xl" as "m-1-xl",
  M2_XL: "m-2-xl" as "m-2-xl",
  M3_XL: "m-3-xl" as "m-3-xl",

  // RIGHT + LEFT

  MX0: "mx-0" as "mx-0",
  MX1: "mx-1" as "mx-1",
  MX2: "mx-2" as "mx-2",
  MX3: "mx-3" as "mx-3",
  MX0_SM: "mx-0-sm" as "mx-0-sm",
  MX1_SM: "mx-1-sm" as "mx-1-sm",
  MX2_SM: "mx-2-sm" as "mx-2-sm",
  MX3_SM: "mx-3-sm" as "mx-3-sm",
  MX0_MD: "mx-0-md" as "mx-0-md",
  MX1_MD: "mx-1-md" as "mx-1-md",
  MX2_MD: "mx-2-md" as "mx-2-md",
  MX3_MD: "mx-3-md" as "mx-3-md",
  MX0_LG: "mx-0-lg" as "mx-0-lg",
  MX1_LG: "mx-1-lg" as "mx-1-lg",
  MX2_LG: "mx-2-lg" as "mx-2-lg",
  MX3_LG: "mx-3-lg" as "mx-3-lg",
  MX0_XL: "mx-0-xl" as "mx-0-xl",
  MX1_XL: "mx-1-xl" as "mx-1-xl",
  MX2_XL: "mx-2-xl" as "mx-2-xl",
  MX3_XL: "mx-3-xl" as "mx-3-xl",

  // TOP + BOTTOM

  MY0: "my-0" as "my-0",
  MY1: "my-1" as "my-1",
  MY2: "my-2" as "my-2",
  MY3: "my-3" as "my-3",
  MY0_SM: "my-0-sm" as "my-0-sm",
  MY1_SM: "my-1-sm" as "my-1-sm",
  MY2_SM: "my-2-sm" as "my-2-sm",
  MY3_SM: "my-3-sm" as "my-3-sm",
  MY0_MD: "my-0-md" as "my-0-md",
  MY1_MD: "my-1-md" as "my-1-md",
  MY2_MD: "my-2-md" as "my-2-md",
  MY3_MD: "my-3-md" as "my-3-md",
  MY0_LG: "my-0-lg" as "my-0-lg",
  MY1_LG: "my-1-lg" as "my-1-lg",
  MY2_LG: "my-2-lg" as "my-2-lg",
  MY3_LG: "my-3-lg" as "my-3-lg",
  MY0_XL: "my-0-xl" as "my-0-xl",
  MY1_XL: "my-1-xl" as "my-1-xl",
  MY2_XL: "my-2-xl" as "my-2-xl",
  MY3_XL: "my-3-xl" as "my-3-xl",

  // LEFT

  ML0: "ml-0" as "ml-0",
  ML1: "ml-1" as "ml-1",
  ML2: "ml-2" as "ml-2",
  ML3: "ml-3" as "ml-3",
  ML0_SM: "ml-0-sm" as "ml-0-sm",
  ML1_SM: "ml-1-sm" as "ml-1-sm",
  ML2_SM: "ml-2-sm" as "ml-2-sm",
  ML3_SM: "ml-3-sm" as "ml-3-sm",
  ML0_MD: "ml-0-md" as "ml-0-md",
  ML1_MD: "ml-1-md" as "ml-1-md",
  ML2_MD: "ml-2-md" as "ml-2-md",
  ML3_MD: "ml-3-md" as "ml-3-md",
  ML0_LG: "ml-0-lg" as "ml-0-lg",
  ML1_LG: "ml-1-lg" as "ml-1-lg",
  ML2_LG: "ml-2-lg" as "ml-2-lg",
  ML3_LG: "ml-3-lg" as "ml-3-lg",
  ML0_XL: "ml-0-xl" as "ml-0-xl",
  ML1_XL: "ml-1-xl" as "ml-1-xl",
  ML2_XL: "ml-2-xl" as "ml-2-xl",
  ML3_XL: "ml-3-xl" as "ml-3-xl",

  // RIGHT

  MR0: "mr-0" as "mr-0",
  MR1: "mr-1" as "mr-1",
  MR2: "mr-2" as "mr-2",
  MR3: "mr-3" as "mr-3",
  MR0_SM: "mr-0-sm" as "mr-0-sm",
  MR1_SM: "mr-1-sm" as "mr-1-sm",
  MR2_SM: "mr-2-sm" as "mr-2-sm",
  MR3_SM: "mr-3-sm" as "mr-3-sm",
  MR0_MD: "mr-0-md" as "mr-0-md",
  MR1_MD: "mr-1-md" as "mr-1-md",
  MR2_MD: "mr-2-md" as "mr-2-md",
  MR3_MD: "mr-3-md" as "mr-3-md",
  MR0_LG: "mr-0-lg" as "mr-0-lg",
  MR1_LG: "mr-1-lg" as "mr-1-lg",
  MR2_LG: "mr-2-lg" as "mr-2-lg",
  MR3_LG: "mr-3-lg" as "mr-3-lg",
  MR0_XL: "mr-0-xl" as "mr-0-xl",
  MR1_XL: "mr-1-xl" as "mr-1-xl",
  MR2_XL: "mr-2-xl" as "mr-2-xl",
  MR3_XL: "mr-3-xl" as "mr-3-xl",

  // TOP

  MT0: "mt-0" as "mt-0",
  MT1: "mt-1" as "mt-1",
  MT2: "mt-2" as "mt-2",
  MT3: "mt-3" as "mt-3",
  MT0_SM: "mt-0-sm" as "mt-0-sm",
  MT1_SM: "mt-1-sm" as "mt-1-sm",
  MT2_SM: "mt-2-sm" as "mt-2-sm",
  MT3_SM: "mt-3-sm" as "mt-3-sm",
  MT0_MD: "mt-0-md" as "mt-0-md",
  MT1_MD: "mt-1-md" as "mt-1-md",
  MT2_MD: "mt-2-md" as "mt-2-md",
  MT3_MD: "mt-3-md" as "mt-3-md",
  MT0_LG: "mt-0-lg" as "mt-0-lg",
  MT1_LG: "mt-1-lg" as "mt-1-lg",
  MT2_LG: "mt-2-lg" as "mt-2-lg",
  MT3_LG: "mt-3-lg" as "mt-3-lg",
  MT0_XL: "mt-0-xl" as "mt-0-xl",
  MT1_XL: "mt-1-xl" as "mt-1-xl",
  MT2_XL: "mt-2-xl" as "mt-2-xl",
  MT3_XL: "mt-3-xl" as "mt-3-xl",


  // BOTTOM

  MB0: "mb-0" as "mb-0",
  MB1: "mb-1" as "mb-1",
  MB2: "mb-2" as "mb-2",
  MB3: "mb-3" as "mb-3",
  MB0_SM: "mb-0-sm" as "mb-0-sm",
  MB1_SM: "mb-1-sm" as "mb-1-sm",
  MB2_SM: "mb-2-sm" as "mb-2-sm",
  MB3_SM: "mb-3-sm" as "mb-3-sm",
  MB0_MD: "mb-0-md" as "mb-0-md",
  MB1_MD: "mb-1-md" as "mb-1-md",
  MB2_MD: "mb-2-md" as "mb-2-md",
  MB3_MD: "mb-3-md" as "mb-3-md",
  MB0_LG: "mb-0-lg" as "mb-0-lg",
  MB1_LG: "mb-1-lg" as "mb-1-lg",
  MB2_LG: "mb-2-lg" as "mb-2-lg",
  MB3_LG: "mb-3-lg" as "mb-3-lg",
  MB0_XL: "mb-0-xl" as "mb-0-xl",
  MB1_XL: "mb-1-xl" as "mb-1-xl",
  MB2_XL: "mb-2-xl" as "mb-2-xl",
  MB3_XL: "mb-3-xl" as "mb-3-xl",

};

export type Spacing = typeof Spacing[keyof typeof Spacing];
